# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.10
_src_path: https://github.com/jupyterlab/extension-template
author_email: haudin.florence@gmail.com
author_name: Florence Haudin
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: jupyter-theme-editor
mimetype: ''
mimetype_name: ''
project_short_description: Extension to create a theme.
python_name: jupyter_theme_editor
repository: https://github.com/jupyterlab-contrib/jupyterlab-theme-editor.git
test: true
viewer_name: ''

